services:
  auth:
    container_name: auth_service
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    ports:
      - "127.0.0.1:8801:8801"
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-user-uploads:${USER_UPLOADS_DIR}

  board:
    container_name: board_service
    build:
      context: .
      dockerfile: ./cmd/board/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    ports:
      - "127.0.0.1:8802:8802"
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-user-uploads:${USER_UPLOADS_DIR}

  user:
    container_name: user_service
    build:
      context: .
      dockerfile: ./cmd/user/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    ports:
      - "127.0.0.1:8803:8803"
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-user-uploads:${USER_UPLOADS_DIR}

  postgres:
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "config_file=/configs/postgresql.conf"
      - "-c"
      - "hba_file=/configs/pg_hba.conf"
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-db-data:/var/lib/postgresql/data
      - pumpkin-all-logs:/pg_logs
      - ./database:/configs:ro

  redis:
    container_name: redis
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - pumpkin-redis-data:/var/lib/redis/data
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - Pumpkin-network

  grafana:
    container_name: grafana
    image: grafana/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

  node_exporter:
    depends_on:
      - prometheus
    image: quay.io/prometheus/node-exporter:latest

networks:
  Pumpkin-network:
    name: Pumpkin-network
    driver: bridge

volumes:
  pumpkin-db-data:
  pumpkin-redis-data:
  pumpkin-user-uploads:
  pumpkin-all-logs:
