services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    ports:
      - "127.0.0.1:8800:8800"
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-user-uploads:${USER_UPLOADS_DIR}

  postgres:
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
      - "-c"
      - "hba_file=/etc/pg_hba.conf"
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-db-data:/var/lib/postgresql/data
      - pumpkin-all-logs:/pg_logs
      - ./database/postgresql.conf:/etc/postgresql.conf:ro
      - ./database/pg_hba.conf:/etc/pg_hba.conf:ro

  redis:
    container_name: redis
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - pumpkin-redis-data:/var/lib/redis/data
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - Pumpkin-network

  grafana:
    container_name: grafana
    image: grafana/grafana

networks:
  Pumpkin-network:
    name: Pumpkin-network
    driver: bridge

volumes:
  pumpkin-db-data:
  pumpkin-redis-data:
  pumpkin-user-uploads:
  pumpkin-all-logs:
