version: "3.3"

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      elastic:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"
    networks:
      - Pumpkin-network
    volumes:
      - type: bind
        source: /var/log/
        target: /var/log/
      - type: bind
        source: /opt/images/
        target: /opt/images/
      - type: bind
        source: /opt/attaches/
        target: /opt/attaches/
  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - Pumpkin-network
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/initdb.sql
      - younote-db-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - younote-redis-data:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - .env
    networks:
      - YouNote-network

networks:
  YouNote-network:
    name: YouNote-network
    driver: bridge

volumes:
  younote-db-data:
  younote-redis-data:
  younote-elastic-data:
