DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS user_uploaded_file CASCADE;

DROP TABLE IF EXISTS board CASCADE;

DROP TABLE IF EXISTS user_to_board CASCADE;

DROP TABLE IF EXISTS kanban_column;

DROP TABLE IF EXISTS "card";

DROP TABLE IF EXISTS tag;

DROP TABLE IF EXISTS tag_to_card;

DROP TABLE IF EXISTS card_update;

DROP TABLE IF EXISTS "notification";

DROP TABLE IF EXISTS checklist_field;
