DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS user_uploaded_file CASCADE;

DROP TABLE IF EXISTS board CASCADE;

DROP TABLE IF EXISTS user_to_board CASCADE;

DROP TABLE IF EXISTS kanban_column CASCADE;

DROP TABLE IF EXISTS "card" CASCADE;

DROP TABLE IF EXISTS tag CASCADE;

DROP TABLE IF EXISTS tag_to_card CASCADE;

DROP TABLE IF EXISTS card_update CASCADE;

DROP TABLE IF EXISTS "notification" CASCADE;

DROP TABLE IF EXISTS checklist_field CASCADE;
